### ISSUE TITLE
Loading an external image

### ISSUE THREAD

**Issue by SurajKumarM98** [madeyoga/Handwritten-Text-Recognition#1]
Hello! 
       Could you please teach me how to load an external image into the trained model?
Thank you!

**Comment by madeyoga** [comment]
## 1. Create Dataset (Skip this step if you already have your image labeled)
Gather images and label them.

There are many ways to label. Simple way is to create txt file. And write your custom dataset (external image) filepaths and the labels in, with format 

```
<path/to/your/file> <single-word>
```

For example:
- Assume the filepath of this image is `path/to/your/dataset/folder/sample1.jpg`
![sample1.jpg](https://img.favpng.com/10/20/21/logo-point-angle-brand-font-png-favpng-SLYrjAfugaWT3iiSwGjXHQaxP.jpg)
- Then write this to your txt file
```txt
path/to/your/dataset/folder/sample1.jpg hope
```
- **Example with multiple images**
```txt
path/to/your/dataset/folder/sample1.jpg hope
path/to/your/dataset/folder/sample2.jpg dummy
path/to/your/dataset/folder/sample3.jpg dummydummy
```

### Load txt File
Load your txt file. For example: 
```py
with open('path/to/your/txt_filename.txt') as f:
    external_contents = f.readlines()

external_entries = [line.strip() for line in external_contents] 

external_entries[0] # will give you a string `path/to/your/dataset/folder/sample1.jpg hope`
```

## 2. Load and Preprocess Dataset/Image (Generate train set)
Loop through `external_entries ` and load the image using `cv2`.
```py
# Use lists from notebook at `In [6]`
train_images = []
train_labels = []
train_input_length = []
train_label_length = []
train_original_text = []

max_label_len = 0

for entry in external_entries : 
    # Split entry by whitespace to get filepath and word
    filepath, word = entry.split(' ')

    # Load image
    img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)

    # Function `process_image` See notebook at `In [9]`.
    preprocessed_img = process_image(img)

    # Function `encode_to_labels` See notebook at `In [6]`
    encoded_labels= encode_to_labels(word)
    
    # Append to `train` lists. 
    train_images.append(preprocessed_img)
    train_labels.append(encoded_labels)
    train_input_length.append(31)
    train_label_length.append(len(word))
    train_original_text.append(word)
    
    # Update max_label_len
    if len(word) > max_label_len:
          max_label_len = len(word)
```

### Continue to `In [10]` **Generate train & validation set**

**Comment by madeyoga** [comment]
I'll check back in a few days to see if that works for you!
